name: Auto Run Script

# 定时任务：每天早上 8 点运行
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:  # 手动触发支持
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # 使用 Python 3.8

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: 运行脚本
    - name: Run the Python script
      run: python 工学云签到.py
